### ISSUE TITLE
Is there a plan to open source the code of model and training scripts?

### ISSUE THREAD

**Issue by ccyousa** [seq-to-mind/planning_dial_summ#1]
Thank you for your job, I'm very interested in this work and want to try it out. 
So, is there a plan to open source the code of model and training scripts?

**Comment by seq-to-mind** [comment]
Hi,

The data provided in this repo can be used to train existing summarization models, such as HuggingFace Transformers and our implementation of `coref_dial_summ'.
We will update our summarizer version later.

Thanks

**Comment by ccyousa** [comment]
Thanks, I'll try these repos.
